-- MySQL Script generated by MySQL Workbench
-- 02/18/17 21:11:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbinfox
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbinfox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbinfox` DEFAULT CHARACTER SET latin1 ;
USE `dbinfox` ;

-- -----------------------------------------------------
-- Table `dbinfox`.`tbclientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinfox`.`tbclientes` (
  `idcli` INT(11) NOT NULL AUTO_INCREMENT,
  `nomecli` VARCHAR(50) NOT NULL,
  `endcli` VARCHAR(100) NULL DEFAULT NULL,
  `fonecli` VARCHAR(50) NOT NULL,
  `emailcli` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idcli`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbinfox`.`tbos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinfox`.`tbos` (
  `os` INT(11) NOT NULL AUTO_INCREMENT,
  `data_os` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `equipamento` VARCHAR(150) NOT NULL,
  `defeito` VARCHAR(150) NOT NULL,
  `servico` VARCHAR(150) NULL DEFAULT NULL,
  `tecnico` VARCHAR(30) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `idcli` INT(11) NOT NULL,
  PRIMARY KEY (`os`),
  INDEX `idcli` (`idcli` ASC),
  CONSTRAINT `tbos_ibfk_1`
    FOREIGN KEY (`idcli`)
    REFERENCES `dbinfox`.`tbclientes` (`idcli`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbinfox`.`tbusuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinfox`.`tbusuarios` (
  `iduser` INT(11) NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `fone` VARCHAR(15) NULL DEFAULT NULL,
  `login` VARCHAR(15) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `login` (`login` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
